import { openai } from "@ai-sdk/openai";
import { fireworks } from "@ai-sdk/fireworks";
import { wrapLanguageModel, extractReasoningMiddleware } from "ai";

export const MODEL = openai('gpt-4.1');

// If you want to use a Fireworks model, uncomment the following code and set the FIREWORKS_API_KEY in Vercel
// NOTE: Use middleware when the reasoning tag is different than think. (Use ChatGPT to help you understand the middleware)
// export const MODEL = wrapLanguageModel({
//     model: fireworks('fireworks/deepseek-r1-0528'),
//     middleware: extractReasoningMiddleware({ tagName: 'think' }), // Use this only when using Deepseek
// });


function getDateAndTime(): string {
    const now = new Date();
    const dateStr = now.toLocaleDateString('en-US', {
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric'
    });
    const timeStr = now.toLocaleTimeString('en-US', {
        hour: 'numeric',
        minute: '2-digit',
        timeZoneName: 'short'
    });
    return `The day today is ${dateStr} and the time right now is ${timeStr}.`;
}

export const DATE_AND_TIME = getDateAndTime();

export const AI_NAME = "Coach Venus";
export const OWNER_NAME = "Sophia Zou";

export const WELCOME_MESSAGE = `Hello! I'm ${AI_NAME}, an AI assistant trained on evidence-based fitness principles designed to help women like you learn to create a strong, aesthetic physique to make you feel and look like your best self! Created by ${OWNER_NAME}. Please note: Responses are generated by an AI system and may be inaccurate or incomplete. Coach Venus does not provide professional, legal, medical, financial, or other regulated advice. Please use at your own risk.

Here are some ideas you can ask me:

Training fundamentals:
(beginner lifting frequency,
sets and reps, rest times,
progressive overload,
exercise selection by movement pattern,
split recommendations,
expected rate of progress)

Women’s physique focus:
(glute-focused training basics,
shoulders/back for physique shape,
common beginner misconceptions,
body recomposition expectations)

Nutrition:
(protein basics,
calorie deficit,
maintenance,
surplus,
meal composition)`

export const CLEAR_CHAT_TEXT = "New";

export const MODERATION_DENIAL_MESSAGE_SEXUAL = "I can't discuss explicit sexual content. Please ask something else.";
export const MODERATION_DENIAL_MESSAGE_SEXUAL_MINORS = "I can't discuss content involving minors in a sexual context. Please ask something else.";
export const MODERATION_DENIAL_MESSAGE_HARASSMENT = "I can't engage with harassing content. Please be respectful.";
export const MODERATION_DENIAL_MESSAGE_HARASSMENT_THREATENING = "I can't engage with threatening or harassing content. Please be respectful.";
export const MODERATION_DENIAL_MESSAGE_HATE = "I can't engage with hateful content. Please be respectful.";
export const MODERATION_DENIAL_MESSAGE_HATE_THREATENING = "I can't engage with threatening hate speech. Please be respectful.";
export const MODERATION_DENIAL_MESSAGE_ILLICIT = "I can't discuss illegal activities. Please ask something else.";
export const MODERATION_DENIAL_MESSAGE_ILLICIT_VIOLENT = "I can't discuss violent illegal activities. Please ask something else.";
export const MODERATION_DENIAL_MESSAGE_SELF_HARM = "I can't discuss self-harm. If you're struggling, please reach out to a mental health professional or crisis helpline.";
export const MODERATION_DENIAL_MESSAGE_SELF_HARM_INTENT = "I can't discuss self-harm intentions. If you're struggling, please reach out to a mental health professional or crisis helpline.";
export const MODERATION_DENIAL_MESSAGE_SELF_HARM_INSTRUCTIONS = "I can't provide instructions related to self-harm. If you're struggling, please reach out to a mental health professional or crisis helpline.";
export const MODERATION_DENIAL_MESSAGE_VIOLENCE = "I can't discuss violent content. Please ask something else.";
export const MODERATION_DENIAL_MESSAGE_VIOLENCE_GRAPHIC = "I can't discuss graphic violent content. Please ask something else.";
export const MODERATION_DENIAL_MESSAGE_DEFAULT = "Your message violates our guidelines. I can't answer that.";
export const MODERATION_DENIAL_MESSAGE_MEDICAL = "I’m not able to provide medical advice or diagnose conditions. It would be best to speak with a licensed healthcare professional. If you’d like, I can still share general fitness or recovery guidelines.";
export const MODERATION_DENIAL_MESSAGE_EATING_DISORDER = "I can’t support advice that involves extreme restriction or harmful eating behaviors. Your health matters more than short-term results. If you're struggling with food or body image, it could really help to talk to a qualified professional. I’m here to support you with safe, sustainable fitness guidance.";
export const MODERATION_DENIAL_MESSAGE_EXTREME_WEIGHT_LOSS = "I can’t help with extreme or rapid weight loss methods. If your goal is fat loss, I can help you do it in a safe, sustainable way that supports your energy, hormones, and long-term results.";
export const MODERATION_DENIAL_MESSAGE_STEROIDS_OR_PEDs = "I’m not able to provide guidance on steroids or performance-enhancing drugs. If your goal is to build muscle or improve your physique, I can help you do that safely and effectively with training and nutrition.";
export const MODERATION_DENIAL_MESSAGE_INJURY_OR_PAIN = "I’m not able to assess or treat injuries. If you're experiencing pain or something doesn’t feel right, it’s important to get evaluated by a qualified professional. I can help with general training adjustments if you’d like.";
export const MODERATION_DENIAL_MESSAGE_PREGNANCY_OR_HORMONAL = "I’m not able to give specific guidance for situations like pregnancy or hormonal conditions. A qualified healthcare provider or specialist would be the best person to guide you safely. I can still share general fitness principles if helpful.";

export const PINECONE_TOP_K = 40;
export const PINECONE_INDEX_NAME = "my-ai";
